"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useRef, useState } from "react";

import { createThesis, getTheses } from "@/lib/api/client";
import { formatSecDate } from "@/lib/formatters";
import type { ThesisCreateInput, ThesisListResponse, ThesisSignal, ThesisStatus } from "@/types/thesis";
import { ConvictionBadge, SignalBadge, StatusBadge } from "./thesis-badges";
import { ThesisForm } from "./thesis-form";
import { ThesisError, ThesisLoading } from "./thesis-states";

type LoadState = { status: "loading" } | { status: "error"; message: string } | { status: "success"; data: ThesisListResponse };
const initialState: LoadState = { status: "loading" };

export function ThesisJournal({ initialTicker = "" }: { initialTicker?: string }) {
  const router = useRouter();
  const createButtonRef = useRef<HTMLButtonElement>(null);
  const [state, setState] = useState<LoadState>(initialState);
  const [version, setVersion] = useState(0);
  const [creating, setCreating] = useState(Boolean(initialTicker));
  const [busy, setBusy] = useState(false);
  const [mutationError, setMutationError] = useState("");
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<ThesisStatus | "ALL">("ALL");
  const [signal, setSignal] = useState<ThesisSignal | "ALL">("ALL");
  const [overdue, setOverdue] = useState<"ALL" | "OVERDUE" | "CURRENT">("ALL");

  useEffect(() => {
    const controller = new AbortController();
    getTheses({}, controller.signal).then((data) => setState({ status: "success", data })).catch((error: unknown) => {
      if (error instanceof DOMException && error.name === "AbortError") return;
      setState({ status: "error", message: error instanceof Error ? error.message : "An unexpected thesis error occurred." });
    });
    return () => controller.abort();
  }, [version]);

  const visible = useMemo(() => {
    if (state.status !== "success") return [];
    const normalizedQuery = query.trim().toUpperCase();
    return state.data.theses.filter((thesis) =>
      (!normalizedQuery || thesis.ticker.includes(normalizedQuery) || thesis.company_name.toUpperCase().includes(normalizedQuery) || thesis.title.toUpperCase().includes(normalizedQuery)) &&
      (status === "ALL" || thesis.status === status) &&
      (signal === "ALL" || thesis.signal === signal) &&
      (overdue === "ALL" || (overdue === "OVERDUE" ? thesis.is_overdue : !thesis.is_overdue)),
    );
  }, [overdue, query, signal, state, status]);

  if (state.status === "loading") return <ThesisLoading />;
  if (state.status === "error") return <ThesisError message={state.message} onRetry={() => { setState(initialState); setVersion((value) => value + 1); }} />;

  const { counts } = state.data;
  return <div className="space-y-5">
    <section className="border border-border bg-panel p-5 sm:p-6">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-positive">Persistent research journal</p><h2 className="mt-2 text-xl font-semibold text-foreground">Investment theses</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-secondary">Record the original proposition, explicit risks, invalidation criteria, and evidence. Signals are manual—not generated by AI.</p></div>
        <button ref={createButtonRef} type="button" onClick={() => { setCreating(true); setMutationError(""); }} className="shrink-0 border border-positive px-4 py-2.5 font-mono text-xs font-semibold uppercase tracking-wider text-positive outline-none hover:bg-positive/10 focus-visible:ring-2 focus-visible:ring-positive">Create thesis</button>
      </div>
      <dl className="mt-5 grid grid-cols-2 border-l border-t border-border sm:grid-cols-4">
        {[["Total", counts.total], ["Active", counts.active], ["Overdue", counts.overdue], ["Review required", counts.review_required]].map(([label, value]) => <div key={label} className="border-b border-r border-border bg-sidebar p-3"><dt className="font-mono text-[9px] uppercase tracking-wider text-secondary">{label}</dt><dd className={`financial-figure mt-1 text-lg font-semibold ${label === "Overdue" && Number(value) > 0 ? "text-warning" : "text-foreground"}`}>{value}</dd></div>)}
      </dl>
    </section>

    {creating ? <ThesisForm initialTicker={initialTicker} busy={busy} onCancel={() => { setCreating(false); setMutationError(""); requestAnimationFrame(() => createButtonRef.current?.focus()); }} onSubmit={async (input) => {
      setBusy(true); setMutationError("");
      try { const created = await createThesis(input as ThesisCreateInput); router.push(`/thesis/${encodeURIComponent(created.ticker)}`); }
      catch (error) { setMutationError(error instanceof Error ? error.message : "The thesis could not be created."); }
      finally { setBusy(false); }
    }} /> : null}
    {mutationError ? <p className="border border-warning/50 bg-warning/5 p-3 text-sm text-warning" role="alert">{mutationError}</p> : null}

    <section className="border border-border bg-panel p-4" aria-label="Thesis filters">
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <label className="font-mono text-[9px] uppercase tracking-wider text-secondary">Search journal<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ticker, company, or title" className="mt-2 w-full border border-border bg-background px-3 py-2 text-sm normal-case tracking-normal text-foreground outline-none focus-visible:ring-2 focus-visible:ring-positive" /></label>
        <FilterSelect label="Status" value={status} onChange={(value) => setStatus(value as ThesisStatus | "ALL")} options={["ALL", "DRAFT", "ACTIVE", "INVALIDATED", "ARCHIVED"]} />
        <FilterSelect label="Signal" value={signal} onChange={(value) => setSignal(value as ThesisSignal | "ALL")} options={["ALL", "STRENGTHENING", "STABLE", "WEAKENING", "REVIEW_REQUIRED"]} />
        <FilterSelect label="Review timing" value={overdue} onChange={(value) => setOverdue(value as typeof overdue)} options={["ALL", "OVERDUE", "CURRENT"]} />
      </div>
    </section>

    {visible.length === 0 ? <section className="border border-border bg-panel p-8 text-center"><h2 className="text-lg font-semibold text-foreground">{state.data.theses.length === 0 ? "No theses recorded" : "No theses match these filters"}</h2><p className="mx-auto mt-2 max-w-xl text-sm text-secondary">{state.data.theses.length === 0 ? "Create the first thesis to begin comparing new evidence with the original investment case." : "Adjust the search, status, signal, or review-timing filters."}</p></section> :
      <ul className="grid gap-4 xl:grid-cols-2">{visible.map((thesis) => <li key={thesis.id}><Link href={`/thesis/${encodeURIComponent(thesis.ticker)}`} className="block h-full border border-border bg-panel p-5 outline-none hover:border-secondary/60 focus-visible:ring-2 focus-visible:ring-positive"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-sm font-semibold text-positive">{thesis.ticker}</p><p className="mt-1 text-sm text-secondary">{thesis.company_name}</p></div><div className="flex flex-wrap gap-2"><StatusBadge status={thesis.status} /><SignalBadge signal={thesis.signal} /></div></div><h3 className="mt-4 text-base font-semibold text-foreground">{thesis.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-secondary">{thesis.summary}</p><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-border pt-4"><ConvictionBadge conviction={thesis.conviction} /><p className={`font-mono text-[10px] ${thesis.is_overdue ? "text-warning" : "text-secondary"}`}>{thesis.review_due_date ? `${thesis.is_overdue ? "Overdue" : "Review due"} ${formatSecDate(thesis.review_due_date)}` : "No review date"}</p></div><p className="mt-3 font-mono text-[9px] uppercase tracking-wider text-secondary">{`${thesis.evidence_counts.supporting} supporting · ${thesis.evidence_counts.contradicting} contradicting · ${thesis.evidence_counts.neutral} neutral`}</p></Link></li>)}</ul>}
  </div>;
}

function FilterSelect({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) {
  return <label className="font-mono text-[9px] uppercase tracking-wider text-secondary">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full border border-border bg-background px-3 py-2 text-sm tracking-normal text-foreground outline-none focus-visible:ring-2 focus-visible:ring-positive">{options.map((option) => <option key={option} value={option}>{option.toLowerCase().replaceAll("_", " ")}</option>)}</select></label>;
}
